const RESTAURANTS_LOADING = "RESTAURANTS_LOADING";
const RESTAURANTS_SUCCESS = "RESTAURANTS_SUCCESS";
const RESTAURANTS_FAILURE = "RESTAURANTS_FAILURE";
const SEARCH_RESTAURANTS = "SEARCH_RESTAURANTS";

export { RESTAURANTS_LOADING, RESTAURANTS_SUCCESS, RESTAURANTS_FAILURE, SEARCH_RESTAURANTS };